### PR TITLE
Show errno for close failure

### PR DESCRIPTION
**Pull request by k0kubun**
I experienced "fptr_finalize failed." error but it was hard to resolve since I coudln't know what kind of error happened. I want to show errno for close in the error message.
In addition, I moved the code block to catch errno for close properly.

### CODE REVIEW

**Comment by tsahara** [comment]
How did you fail close(2)?  I found we have to rewrite more lines to capture an error code correctly.

**Comment by k0kubun** [comment]
I saw 6 (ENXIO) and 9 (EBADF).

**Comment by tsahara** [comment]
Is https://github.com/iij/mruby-errno not appliacable to your case?

**Comment by k0kubun** [comment]
Applied mruby-errno. https://github.com/iij/mruby-io/pull/67/commits/bddf71386152d983468e351d67b074ada5c0a38e

**Comment by tsahara** [comment]
If you build mruby with mruby-errno by including it in your `build_config.rb`, you can get the value of `errno` from the exception object.

```
% cat a.rb
begin
  File.open("/nothing")
rescue => e
  puts "errno=#{e.errno}, e=#{e.message}"
end

% mruby a.rb
errno=2, e=No such file or directory - open

% ruby a.rb
errno=2, e=No such file or directory @ rb_sysopen - /nothing
%              
```

Does it help you investigate the error?

**Comment by k0kubun** [comment]
I found mruby-errno convenient and helpful to investigate errors.

https://github.com/iij/mruby-io/pull/67/commits/8effb6cb285c308025d50287013d8e557be135c4 is a little ugly and I guess you don't want to build mruby without mruby-errno in many cases. So closing this.

**Pull request closed without merging**
