### PR TITLE
add File.identical?

### PR DESCRIPTION
**Pull request by takahashim**

### CODE REVIEW

**Comment by tsahara** [comment]
It looks too much dependent on the implementation detail of the file system.

**Comment by takahashim** [comment]
Thanks for your comment!
Yes, it's just line-by-line porting from CRuby's definition in `#ifndef _WIN32` ... `#endif`
https://github.com/ruby/ruby/blob/trunk/file.c#L1909-L1915

Should I use `#ifdef` macro too, and raise error in Windows? (I cannot confirm it on windows yet...)

**Comment by tsahara** [comment]
I didn't make my concern clear on the previous comment, sorry.

Is this method so useful as to be implemented in a library?  It implements only one way of identity checks on the filesystems.  I don't know how many users of mruby-io will use this method.

**Comment by takahashim** [comment]
> Is this method so useful as to be implemented in a library?

I'm not sure how useful it is in everyday situations (honestly, I have not used it directly), but `FileUtils` library uses this method in some methods, such as `FileUtils.ln_s`, `FileUtils.cp`, `FileUtils.mv` and `FileUtils.install` (In their methods, when same file is in src and dest, raises ArgumentError).

Even if you, as a maintainer of mruby-io, don't feel the need of this method, I'm OK.  I think I can implement similar method in pure ruby with mruby-file-stat.

**Comment by tsahara** [comment]
I think there are not so many usecases of this method to merge it into the default setup of mruby-io for now.

**Comment by takahashim** [comment]
Thanks for feedback!  I'll try to do without this patch.

**Comment by tsahara** [comment]
I didn't merge this but I thank you for the suggestion and detailed explanation.

**Pull request closed without merging**
